environment:
  ROOT_DIR: ${ROOT_DIR}


schema:
- &SIDE_EFFECT_LIST
  cls_name: Side_Effect_List
  slots: true
  description: Data_Class needed to create a list side effect
  fields:
  - name: value
    description: List of values for the side effect
    type: List[Any] | None
    default: []
  - name: count
    type: int
    default: 0
    description: Track the number of times the side effect has been called
- &PARENTS
  cls_name: Parents
  slots: true
  description: Store the names, values, and types of an objects parents
  fields:
  - name: names
    description: The name of each parent
    type:  List[str] | None
    default: null
  - name: values
    description: The value of each parent
    type: List[Any] | None
    default: null
  - name: types
    description: The type of each parent
    type: List[str] | None
    default: null
- &DATA
  cls_name: Data
  slots: true
  description: Store data used by the functions in a module
  fields:
  - name: module
    description: Module containing the object to patch
    type:  ModuleType | None
    default: null
  - name: name
    description: Dot-delimited name of the object to patch
    type: str | List[str] | None
    default: null
  - name: method
    description: Method for how to patch the object
    type: str | None
    default: null
  - name: value
    description: Value used to patch an object
    type: Any | None
    default: null
  - name: timestamp
    description: A timestamp of key used to access patches
    type: int
    default: 0
  - name: patches
    description: A list of patches to process
    type: object | None
    default: []
  - name: parents
    description: Store data for an object's parents
    type: Parents | None
    default: null
  - name: names
    description: Store object parent names
    type: str | None
    default: []
  - name: patch
    description: The object used as a patch
    type: Any | None
    default: null


operations:
- get_patch
- get_parent
- patch_object


empty_values:
- null
- None
- []
- '[]'
- '{}'
- {}
