config_a: config_a
config_b: '00001'
config_c: 
- config_c
- config_c
config_d: 
  config_d: config_d
config_f: config_f
environment:
  A: A
  B: B
  C: C
  D: D
schema:
- &EXAMPLE
  cls_name: Example
  description: An example of the schema for a dataclass
  slots: true
  fields:
  - name: field_a
    type: dict
    description: an example of a dataclass field
    repr: false
    default: {}
  - name: field_b
    type: list
    description: an example of a dataclass field
    repr: false
    default: []