schema:
- &PARENTS
  cls_name: Parents
  description: >
    Store the names, values, and types of the
    parents of an object
  slots: False
  fields:
  - name: names
    type: list | None
    description: The names of an object's parents
    default: null
  - name: values
    type: list | None
    description: The values of an object's parents
    default: null
  - name: types
    type: list | None
    description: The types of an object's parents
    default: null
- &DATA
  cls_name: Data
  description: Data used by the functions within the module
  slots: False
  fields:
  - name: parent
    type: Any
    description: An object's parent
    default: null
  - name: name
    type: str | None
    description: Name of an object's parent
    default: null
  - name: parents
    type: Data_Class | None
    description: Store parent data for an object
    default: null
  - name: names
    type: list | None
    description: The names of an object's parents
    default: null


kinds:
- dict
- object


undefined:
- ''
- .
- None
- null
