schema:
- &DATA
  cls_name: Data
  description: Data used by the functions within the module
  slots: False
  fields:
  - name: globals
    type: dict | None
    description: Global configurations defined in YAML files
    default: {}
  - name: tests
    type: list | None
    description: Tests defined in YAML files
    default: []


empty_values:
- None
- null
- []
- {}
- ''
- '[]'
- '{}'


operations:
- get_tree_roots
- get_tree_branches
- prune_tree_branches
