environment:
  ROOT_DIR: ${ROOT_DIR}


schema:
- &TEST
  cls_name: Test
  description: Contains all of the fields needed to collate and run a test
  slots: true
  fields:
  - name: resources
    type: str | list | None
    description: Path to a directory containing resources to use for tests
    default: ''
  - name: exclude
    type: str | list | None
    description: Functions to exclude from testing and coverage
    default: []
  - name: module
    type: Any | None
    description: A module or the location to a module in the file system
    default: null
  - name: function
    type: str | None
    description: Name of the function to test
    default: ''
  - name: function_name
    type: str | None
    description: Name of the function to test
    default: ''
  - name: cast_arguments
    description: Cast whole or parts of a function's arguments
    type: List[dict | Cast] | None
    default: []
  - name: cast_output
    description: Cast whole or parts of a function's result
    type: List[dict | Cast] | None
    default: []
  - name: description
    type: str | None
    description: Description for a module, test, or case
    default: ''
  - name: patches
    type: list | None
    description: List containing info on objects to patch
    default: ''
  - name: environment
    type: dict | None
    default: {}
    description: Environment variables to use for tests
  - name: arguments
    type: dict | None
    default: {}
    description: Keyword arguments to pass to functions
  - name: assertions
    type: list | None
    default: []
    description: >
      A list of assertions and expected results to verfiy against
      the actual result
  - name: yaml
    type: str | None
    description: Path to a YAML test file
  - name: exception
    type: dict | None
    default: {}
    description: Store any exceptions that occur when runninng a function
  - name: result
    type: Any | None
    default: {}
    description: Store results of running the function
  - name: output
    type: Any | None
    default: null
    description: Store results of running the function
  - name: project_directory
    type: str | None
    default: null
    description: Location of the project's working directory
  # Order matters
  # IDs are formatted last
  - name: id
    type: str | None
    default: null
    description: Unique long ID assigned to each tests
  - name: id_long
    type: str | None
    default: ''
    description: Unique short ID assigned to each tests
  - name: id_short
    type: str | None
    default: ''
    description: Unique ID assigned to each tests
  - name: cast_group
    type: list | None
    default: []
    description: >
      Keep track of which group, arguments of result,
      to cast
  - name: module_location
    type: str | None
    description: Location of a module in the file system
    default: ''
  - name: n
    type: int | None
    description: Store the length of an object
    default: 0
  - name: timestamp
    type: int | None
    description: A timestamp represented as a integer
    default: null
  - name: tests
    type: list | None
    description: Store individual tests
    default: null


empty_values:
- null
- []
- {}
- ''
- None
- 0
- '0'


format_id_short_keys:
  module_location: module
  function_name: function
  description: description
  project_directory: directory
  key: key


main_operations:
- format_environment_refactor
- format_function_refactor
- format_resources_refactor
- format_project_directory_refactor
- format_module_refactor
- format_yaml_refactor
- format_patches_refactor
- format_arguments_refactor
- format_cast_arguments_refactor
- format_description_refactor
- format_id_short_refactor
- format_id_long_refactor
