environment:
  # Set in venv
  ENV: ENV_VARIABLE
  # Set in venv
  DEBUG: DEBUG_VARIABLE
  EXAMPLE: EXAMPLE_VARIABLE
environment_dos:
  ENV_DOS: ENV_VARIABLE_DOS
  DEBUG_DOS: DEBUG_EXAMPLE_DOS
  EXAMPLE_DOS: EXAMPLE_VARIABLE_DOS